### ISSUE TITLE
Cross site scripting vulnerability in $os_version

### ISSUE THREAD

**Issue by MTJailed** [AppTapp/Installer-Repository-Code#1]
A vulnerability exists allowing an attacker to inject javascript into the page from a maliciously crafted url.

The vulnerability lies in the following logic.
A get request is handled by the server as input and stored in $os_version.
Later in the logic this is printed out without any sanitation.

The issue can be fixed by improved input validation and the addition of sanity checks and tag stripping.

**Comment by AppTapp** [comment]
Just pushed an update which ads sanity checks to avoid XSS type attacks. Thank you for reporting.

**Comment by MTJailed** [comment]
Thank you. The vulnerability seems fixed now.
Nice work guys.
