### ISSUE TITLE
ZIP extension is required, please install it.

### ISSUE THREAD

**Issue by okanon** [AppTapp/Installer-Repository-Code#3]
what is "ZIP extension is required, please install it"?
And, Can you do disclosing how to create a simple Tweak?

**Comment by CloneVince** [comment]
The repository need to read the content of package to index it.
On the server, there is PHP and the extension "PHP-ZIP" is required.
For PHP 7.0, for exemple, the package on debian for this extension is PHP7.0-ZIP

In the repository you can find a sample for a simple tweak called "community-123".
Open it and you will understand how create a simple package ;)

**Comment by okanon** [comment]
```
sudo apt install php7.0-zip
```
installed php-zip with Ubuntu 17.10.
```
Generating index for firmware 10.0.
```
Thx!
Tweak will do my best to make it ;)

**Comment by CloneVince** [comment]
Perfect 😊 
Have fun 😉

**Comment by AppTapp** [comment]
As per CloneVince's explanation the issue is closed :)
